#!/usr/bin/env bash

if [ -z ${1+x} ]; then
  echo "Error: please the machine name as an argument"
  exit 2
fi

docker-machine create \
    --driver amazonec2 \
    --amazonec2-instance-type t2.micro \
    --amazonec2-root-size 8 \
    $1
