#!/usr/bin/env bash
set -e

if [ "$MODE" != "DEPLOY" ] ; then
    echo "MODE not set to PRODUCTION, use 'source activate...'"
    exit 2
fi

echo "building em2 image..."
../em2/docker/build.sh ${PRIVATE_KEY_FILE}

sed "s/{{EM2_EXTERNAL_DOMAIN}}/${EM2_EXTERNAL_DOMAIN}/g; s/{{DOMESTIC_DOMAIN}}/${DOMESTIC_DOMAIN}/g" \
 nginx/nginx.conf > nginx/_build.nginx.conf

rm -r nginx/keys/ || true
mkdir nginx/keys/
cp nginx/keys-${DEPLOY_NAME}/* nginx/keys/

echo "building nginx image..."
docker build nginx -t em2-nginx -q

echo ""
eval "docker-compose up -d --build $@"
