#!/usr/bin/env bash
set -e

if [ "$MODE" != "DEPLOY" ] ; then
    echo "MODE not set to PRODUCTION, use 'source activate...'"
    exit 2
fi

echo "building em2 image..."
../em2/docker/build.sh

sed "s/{{SERVER_NAME}}/${EM2_LOCAL_DOMAIN}/" \
 nginx/nginx.conf > nginx/_build.nginx.conf

rm -r nginx/keys/ || true
mkdir nginx/keys/
cp nginx/keys-${EM2_LOCAL_DOMAIN}/* nginx/keys/

echo "building nginx image..."
docker build nginx -t em2-nginx -q

echo ""
eval "docker-compose up -d --build $@"
