version: '3.2'

volumes:
  postgres: {}
  redis: {}

networks:
  default:
    external:
      # network is created by build.sh to save time on compose up
      name: em2

services:
  logs:
    image: gliderlabs/logspout
    entrypoint:
    - '/bin/logspout'
    - '${LOGSPOUT_ENDPOINT}'
    environment:
      SYSLOG_HOSTNAME: em2-${DEPLOY_NAME}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    volumes:
    - postgres:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: 172.20.0.101
    depends_on:
    - logs

  redis:
    image: redis:4.0-alpine
    volumes:
    - redis:/data
    restart: always
    networks:
      default:
        ipv4_address: 172.20.0.102
    depends_on:
    - logs

  nginx:
    image: em2-nginx
    restart: always
    ports:
    - 443:443
    depends_on:
    - logs

  web:
    image: em2
    environment:
      EM2_COMMAND: web
      EM2_DEBUG: 'true'
      EM2_LOG_TIMES: 'false'
      EM2_PG_HOST: postgres
      EM2_PG_PASSWORD: docker
      EM2_R_HOST: '172.20.0.102'
      EM2_EXTERNAL_DOMAIN: ${EM2_EXTERNAL_DOMAIN}
      EM2_AUTH_SESSION_SECRET: ${EM2_AUTH_SESSION_SECRET}
      EM2_AUTH_INVITATION_SECRET: ${EM2_AUTH_INVITATION_SECRET}
      EM2_AUTH_UPDATE_SESSION_URL: ${EM2_AUTH_UPDATE_SESSION_URL}
      EM2_COMMS_VERIFY_SSL: 'false'
      EM2_FALLBACK_USERNAME: ${EM2_FALLBACK_USERNAME}
      EM2_FALLBACK_PASSWORD: ${EM2_FALLBACK_PASSWORD}
      EM2_FALLBACK_ENDPOINT: ${EM2_FALLBACK_ENDPOINT}
      EM2_FALLBACK_CLS: ${EM2_FALLBACK_CLS}
    restart: always
    networks:
      default:
        ipv4_address: 172.20.0.103
    depends_on:
    - postgres
    - redis
    - logs

  worker:
    image: em2
    environment:
      EM2_COMMAND: worker
      EM2_DEBUG: 'true'
      EM2_LOG_TIMES: 'false'
      EM2_PG_HOST: postgres
      EM2_PG_PASSWORD: docker
      EM2_R_HOST: '172.20.0.102'
      EM2_EXTERNAL_DOMAIN: ${EM2_EXTERNAL_DOMAIN}
      EM2_AUTH_SESSION_SECRET: ${EM2_AUTH_SESSION_SECRET}
      EM2_AUTH_INVITATION_SECRET: ${EM2_AUTH_INVITATION_SECRET}
      EM2_AUTH_UPDATE_SESSION_URL: ${EM2_AUTH_UPDATE_SESSION_URL}
      EM2_COMMS_VERIFY_SSL: 'false'
      EM2_FALLBACK_USERNAME: ${EM2_FALLBACK_USERNAME}
      EM2_FALLBACK_PASSWORD: ${EM2_FALLBACK_PASSWORD}
      EM2_FALLBACK_ENDPOINT: ${EM2_FALLBACK_ENDPOINT}
      EM2_FALLBACK_CLS: ${EM2_FALLBACK_CLS}
    restart: always
    depends_on:
    - postgres
    - redis
    - logs

  auth:
    image: em2
    environment:
      EM2_COMMAND: auth
      EM2_DEBUG: 'true'
      EM2_LOG_TIMES: 'false'
      EM2_PG_HOST: postgres
      EM2_PG_PASSWORD: docker
      EM2_R_HOST: '172.20.0.102'
      EM2_EXTERNAL_DOMAIN: ${EM2_EXTERNAL_DOMAIN}
      EM2_AUTH_SESSION_SECRET: ${EM2_AUTH_SESSION_SECRET}
      EM2_AUTH_INVITATION_SECRET: ${EM2_AUTH_INVITATION_SECRET}
      EM2_AUTH_UPDATE_SESSION_URL: ${EM2_AUTH_UPDATE_SESSION_URL}
      EM2_COMMS_VERIFY_SSL: 'false'
      EM2_FALLBACK_USERNAME: ${EM2_FALLBACK_USERNAME}
      EM2_FALLBACK_PASSWORD: ${EM2_FALLBACK_PASSWORD}
      EM2_FALLBACK_ENDPOINT: ${EM2_FALLBACK_ENDPOINT}
      EM2_FALLBACK_CLS: ${EM2_FALLBACK_CLS}
    restart: always
    networks:
      default:
        ipv4_address: 172.20.0.104
    depends_on:
    - postgres
    - redis
    - logs
